name: teachme
description: "SearchStudyCentr"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  string_validator: ^1.0.2
  dio: ^5.4.0
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

